id: P000753
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1PD181169
  title: སྔ་འགྱུར་གཡག་ཟེ་དགོན་གྱི་འདོན་ཆ་ལས། ནོར་བདག་སེར་པོ་སྐོར་གསུམ་དང་ལྷ་མོའིཚོགས་ཀྱི་སྐོར།
  author: ''
  volumes:
    f6f5d66e530e419ab9e872aec81c106c:
      image_group_id: I1KG16332
      title: ''
      volume_number: 1
      total_pages: 364
      base_file: v001.txt
